# c-142
storage.py(thebelow change need to be done)to solve the error coming in the reference code 142
-------------------
with open('final.csv', encoding="utf8") as f:
